# Expectations and Responsibilities

----------

## Everyone

<h3>Big Picture</h3>
 
Sometimes science can be hard, and the rewards (amazing research findings, papers, etc.) can be few and far between. However, science is always fun when we make the lab a great place to me. In the BABLab, we want everyone to have a positive experience that is free from hostility, so that people can do their best, most productive science. Great labs don’t just happen, they are built. Here is what we can all do to help:
 
- Respect our participants. Whether they are families, undergrads, our adults from the community, they are giving up their time to be involved in research. Always act professionally with participants over the phone and in person, do not leave them waiting. Keep in mind that participants may have different political and religious beliefs, sexual orientations, family compositions, and have had very different life experiences, to you and/or your friends. Please do conduct yourself in a way that respects their unique situation and personhood.
- Respect our child participants. In addition to the above point, remember that children are to be respected as much as adults. Please be aware that even well-meaning adults can sound patronizing sometimes when speaking with children. At the risk of sounding patronizing myself, comments like “cool dress” or “neat sneakers” are fine, but comments like “you are so cute” could come off as patronizing.
- Respect the data and the people who collected it. Data collection, especially in developmental populations, is hard. People put their blood, sweat, and tears into it. They came in on weekends, after hours, on holidays, in rain, hail, and shine (mostly shine – because, Cali) to get it. You might be analyzing data that you did not have to collect. That is a pretty great situation, so make sure you treat that data in the same way you would your own. 
- Respect your lab mates: their culture, religion, beliefs, sexual orientation, and personality quirks. Science is for everyone.
- Respect yourself: your need for time off, your happiness, your other commitments. You are responsible for constructing your boundaries.
- Be supportive of your lab mates: We are a team. Science is about collaboration, not competition.
- Be forgiving of yourself and one another. Being in an academic environment can be challenging. We all make mistakes, and not everyone is on their A-game every day. Whatever happens, try to be understanding, forgive, and move on.
- Tension or hostility in the lab affects everyone and behaving in a bullying, intimidating, rude or disrespectful way will not be tolerated. I expect everyone to be mature and professional while in the lab, this is a workplace and should be treated in that way. If there are any problems which cannot be dealt with in the lab, please tell Bridget.
- Be honest with yourself and others. This means that if you notice a mistake, however embarrassing, admit it, correct it, and move on.
- Check everything several times. Then get someone else to check it. Then check it again. It’s ok to makes mistakes, but mistakes shouldn’t be because of carelessness or rushed work.
- Under no circumstances is it ok to plagiarize, tamper with data, make up data, or omit data. If you are feeling pressured to succeed and think that is interfering with your judgement, you should reach out to Bridget and we can talk about it. However, pressure is something we all face and is not an excuse to engage in academic misconduct.
- If you are struggling with health and/or unhappiness, or if you see someone else that is struggling, please come and see me (Bridget). Everyone goes through rough patches, and we want to help each other out.
- Have a life outside of the lab, take care of your mental and physical health, and don’t ever feel bad for taking time off work, and don’t make others feel bad for doing that either.

 
<h3>Small Picture</h3>
 
There are a few day-to-day things to keep in mind to keep the lab running smoothly.

**Special considerations for virtual format during the covid-19 pandemic**

- The lab is now collecting data online. Please be aware of what you are wearing in the online environment and make sure that it is respectable and that your surroundings are respectable.For instance, if you are with participants, you should be in a non distracting background. We understand that you can’t choose where you’re working from at this time, so please do this within the constraints of your individual situation.
- When we don't have a common lab space in which we meet, it is even more important to check slack and email on a regular basis and be available to respond to messages, set up virtual meetings, etc. 
 
 **General**:
 
- If you’re sick, please take time off, stay home (if we are in person), and take care of yourself. Just slack the lab manager or me (Bridget) to tell us. Because you need it, and also because others don’t need to get sick.
- If you know you might be sick, e.g., you have a minor surgery and don’t know how well you will recover, play it safe and reschedule your appointments ahead of time.
- Working in developmental populations means that work times need to be flexible. If you are collecting data or recruiting participants, you may be expected to work on weekends and holidays. We will make a schedule to share that burden as evenly as possible. When you collect data or recruit participants outside of work hours, I expect that you will take some time off during work hours to compensate.
- Outside of data collection and recruitment, you are not expected to work or come into the lab (if we are in person) on weekends or holidays, and you are not expected to stay late at night.
- You are expected to get your work done to a high standard and you can do that in whatever time of day best suits you and your work style. That being said, being in lab some of the time is important for the lab, and for morale, so you shouldn’t work remotely all of the time (unless we are in a pandemic). (Note: the lab manager is expected to keep more regular hours than other lab members: 8am-5pm, 9am-6pm, 10am-7pm are all reasonable work hours for a lab manager).
- All grad students, post-docs, and paid employees (e.g., lab managers, research associates, and technicians) are expected to attend lab meetings when their schedules allow. We will set a time for the lab meeting each term that best fits everyone’s schedule.
- Volunteers in the lab and other students are expected to attend lab meeting when it suits their schedule and when it is of interest to them.
- Make sure the door to the lab is locked if no one is inside. Turn off the lights if you’re the last one leaving for the day. And water the plants if they are looking sad.
- Keep the lab tidy. Eating in lab is fine, but clean up food waste, crumbs, spills. Put lab equipment back where you found it. Keep common areas uncluttered.
- Lab is a shared space. Unless you have been assigned a permanent desk, do not permanently claim a space. Use space when it is available and remove your belongings when you leave so that others can use the space.
- Dress code is casual, neat, and approachable. When interacting with participants or presenting your work, don’t wear pajamas, dirty clothes, clothes with holes in them, or clothes that are see-through. Jeans are totally fine and even sweatpants/active wear is fine when you are in the lab and collecting data. Remember that when you are collecting data, it will mostly be with kids, so we want to be approachable and comfortable (you might end up on the floor), keep that in mind when considering what to wear. If you want to dress up, that is fine too - as long as you are comfortable and approachable.
- When you are running participants show up 15-20 minutes early to set everything up.
- Be on time for your meetings: respect that others have busy schedules and everyone’s time is valuable.
- Last of all, we all have unique ways of working. I (Bridget) have written a ‘user manual’ so that you can be familiar with mine. Please read it, so that you get to know me a little better from the outset and we can avoid misunderstandings.

----------

## Principal Investigator

All of the above, and I will…

- Support your scientific development and be responsive to your emotional needs
- Give you feedback on a timely basis, including feedback on project ideas, conference posters, talks, manuscripts, figures, grants
- Be available in person and via slack on a regular basis, including regular meetings to discuss your research
- Support your career development in whatever way I can (e.g., by introducing you to other researchers in the field, promoting your work at talks, writing recommendation letters for you, and letting you attend conferences as often as finances permit)
- Help you prepare for the next step of your career, whether it’s a post-doc, a faculty job, or a job outside of academia

----------

## Post-Docs

All of the above, and you will also be expected to…

- Develop your own independent line of research
- Collect data for ongoing projects in the lab, including any group projects. Although the data collection responsibilities of postdocs are lower than others in the lab, taking part in data collection for group projects is everyone’s responsibility
- Write and submit scientific papers (including review papers) in a timely manner
- Help train and mentor students in the lab (both undergraduate and graduate)
- Seek out opportunities to present your work (e.g., at departmental events, in other labs, and at conferences)
- Engage in networking opportunities (e.g., chair a symposium, attend other lab meetings, volunteer as a student representative at conferences)
- Apply for grants (e.g., NRSA, K99, NARSAD). Writing grants is an excellent exercise to find direction in your research, and identify gaps in your training that you can address. It will also give you greater autonomy in the lab, will help your CV, and will help the lab (by freeing up funds, as well as providing a model for the other students to follow). Please see Bridget early about finding different grant mechanisms to apply for, and for example grants
- Apply for jobs (academic or otherwise) when you’re ready, or after you have discussed your progress with Bridget. Postdoctoral training can lead to many different jobs, some in academia, industry and elsewhere. Any of those paths are fine with me (Bridget). Please keep me abreast of your thinking around potential jobs and I will support your career goals in whatever way I can

----------

## Graduate Students
 
All of the above, and you will also be expected to…

- Develop your dissertation research. This includes knowing the literature like the back of your hand. Take ownership of your project and treat it like your baby
- Collect data for the ongoing projects in the lab, which includes any major group projects
- Help mentor undergraduate students in the lab
- Seek out opportunities to present your work (e.g., at departmental events, in other labs, and at conferences)
- Engage in networking opportunities (e.g., attend other lab meetings, volunteer as a student representative at conferences)
- Apply for grants (e.g., NRSA, NSF). Writing grants is an excellent exercise to find direction in your research, and identify gaps in your training that you can address. It will also free up your time from Teaching Assistant (TA) commitments
- Think critically about what you want for your career (academia – research or teaching, industry, science writing, something else). It is never too early to start discussing this with me (Bridget) so that we can make sure you are getting the types of training you need
- Make sure you meet all departmental and internal lab deadlines (e.g., for your exams and thesis) -- and make sure Bridget is aware of them!
- Prioritize time for research. Coursework and TA'ing are important, but it is research that matters for the PhD.

----------

## Lab Managers
 
All of the above, and you will also be expected to…

- Collect data for the ongoing group projects in the lab
- Manage the lab's data backup and ensure backups are done on a consistent basis
- Work on your own research (developed with Bridget’s help) that will either be a review paper, analysis of an existing data set, a study within the group project, or another project that sits outside the group project
- Create research and lab protocols
- Train new lab members on the research and lab protocols
- Monitor adherence to research and lab protocols
- Hire, train, mentor, and assess progress of undergraduate research assistants. This includes setting them up with access to the lab, making sure they have properly onboarded, and making sure they are included in the IRB protocols they are working on
- Schedule and manage the work of undergraduate research assistants
- Maintain IRB protocols for the lab (writing them, renewing them), archive old consent forms, keep any required paperwork up to date and organized
- Maintain the lab website and lab wiki, update the lab manual, add lab events to the lab calendars, manage the lab server, check and respond to the lab e-mail address (bablab.ucla@gmail.com).
- Give new lab members access to the lab wiki, lab GitHub, lab calendars, and add their experiments to the lab server. 
- Assist with the recruitment and scheduling of participants for the group project, and for the smaller projects in the lab
- Help to manage grant budgets and startup funds
- Monitor lab supplies (e.g., toner and paper for the printer, books for students) and order more supplies when needed
- Ensure that lab computers are never updated in the middle of a study

----------

## Enrolled Research Interns

All of the above, and you will also be expected to…

- Develop your own research project in the lab
- Complete your work in a timely manner and make sure you back up your work, and file it appropriately within the lab server (generally, until you have final versions, this will be in your user folder on Box). 
- Make sure that your work is accessible to anyone. That is, comment your code, name files appropriately (see wiki for lab file naming conventiosn), document all aspects of your project, and create a wiki with all important information.  
- Meet regularly with Bridget or whoever is your assigned mentor to discuss your project
- Attend lab meetings and RA meetings when it fits your schedule and if you have interest
- Once you have finalized a piece of work (e.g., script, wiki), send it to the lab manager for approval. Once it has been approved, the lab manager will copy it to main study folder on Box. 
- Note that if you would like to also work as a research assistant in the lab, you must meet with Bridget first. Also please understand that those duties will require a 10 hour per week commitment (separate from anything you are doing for your research project). 

----------

## Research Assistants
 
All of the above, and you will also be expected to…

- Assist other lab members with data collection and analysis
- Work on any projects that your lab mentor has given you
- Complete your work in a timely manner and make sure you back up your work, and file it appropriately within the lab server.
- Make sure that your work is accessible to anyone. That is, leave notes explaining what was done, make sure that spreadsheets and any color coding you used in them are properly annotated
- Develop your weekly schedule by talking to your graduate student mentor or your post-doc mentor. You should be coming in every week, and scheduling enough time to get your work done
- Attend lab meetings when it fits your schedule and if you have interest
- Attend RA meetings
- Keep a log of the work you did in the lab, the dates you were in the lab, and the hours you worked. Send this to your lab mentor when you finish up in the lab. They will use this to write you a letter of reference

----------


## Senior Research Assistants

All of the above, and you will also be expected to…

- Help collect data for the lab's projects, including running participant sessions
- Recruit new participants for the lab's research
- Handle communication with enrolled participants, including scheduling, reminders, session confirmations, maintaining participant records etc. 
- Attend lab meetings and/or RA meetings when it fits your schedule and if you have interest
- Attend a weekly meeting with the lab manager and all SRAs
- Update the Availability calendar and communicate with the lab manager regarding your schedule for lab work and availability for participant sessions

