# Code of Conduct

----------

## Essential Policies

<h3>Student Conduct Code</h3>

UCLA has a Student Conduct Code which can be found [here](https://www.deanofstudents.ucla.edu/Individual-Student-Code). Please take the time to familiarize yourself with it before you start in the lab.

----------

## Scientific Integrity
 
<h3>Reproducible Research</h3>
 
The BABLab at UCLA is committed to performing reproducible research. Reproducible research means that, if you gave someone your raw data and analysis code they should be able to reproduce your results exactly. If they can’t it suggests that something is wrong (e.g., there is a mistake in the pipeline) or that you did not properly document the data collection, cleaning, or analysis process. Neither of these options is good. Therefore, we take steps towards ensuring that all aspects of the data collection, cleaning, and analysis are extremely well documented.
 
For results to be reproducible, you need to be organized and document everything! Take detailed notes on your study design, make sure you save all of the citations for questionnaires you use, if you make up a questionnaire yourself, document that it was made for the study, so that you or someone else doesn’t spend hours looking for the citation later on down the track, thinking it was a validated measure. Keep notes on the different recruitment methods, inclusion/exclusion criteria, participant schedule for study days, all the research protocols, as well as any changes to the protocols that occur during the study. If something goes wrong, or something unusual happens, document that too. Document the parameters for the MRI scanner, document the versions of the software used to collect the data. Before you start collecting data, you should aim to have a private OSF project, or study that forks to the main project, that is as detailed as this example from the [Child Mind Institute](https://childmind.org).
 
Once you have collected data, you need to take detailed notes on data cleaning and analysis. Even if you have preregistered your study design (which you very likely will do), you still need to document this stage, as you may move away from your preregistered cleaning and analysis choices for a variety of reasons. You need to know what those reasons are. You need to write down how you did things every step of the way (and the order that you did things), from any pre-processing of the data, to running models, to statistical tests. Additionally, your code should also be commented, and commented clearly. We all know what it’s like to sit down, quickly write a bunch of code to run an analysis without taking time to comment it, and then having no idea what we did a few months down the road. Comment your code so that every step is understandable by an outsider. Finally, it is highly encouraged that you use some form of version control (e.g., Git in combination with GitHub) to keep track of what code changes you made and when you made them, as well as sharing code with others.
 
In sum, you should write copious notes on your study design and all of the measures before you start the study and place every bit of information on OSF (you will likely also be preregistering your study on OSF). Then you should write beautifully annotated code to clean and analyze your data (e.g., use R-Markdown) and then place that on GitHub. There is nothing more satisfying in science (or life) than a well-organized study. Your future self will thank your current self, and everyone in the lab will thank you too.

<h3>Authorship</h3>
 
Like other labs, we will follow the APA guidelines with respect to authorship:
 

> "Authorship credit should reflect the individual's contribution to the study. An author is considered anyone involved with initial research design, data collection and analysis, manuscript drafting, and final approval. However, the following do not necessarily qualify for authorship: providing funding or resources, mentorship, or contributing research but not helping with the publication itself. The primary author assumes responsibility for the publication, making sure that the data are accurate, that all deserving authors have been credited, that all authors have given their approval to the final draft; and handles responses to inquiries after the manuscript is published."

 
At the start of a new project that occurs within the BABLab, the student or post-doc who is driving the project can expect to be the first author on the primary papers to come out of the project. Bridget will be the senior (i.e., last) author. Students and post-docs who help over the course of the project may also be authors, depending on their contributions. As it is sometimes hard to predict exactly where a project will end up (data collection, cleaning, and analysis in developmental labs can take a long time), the positioning on non-primary and non-senior authors will be decided when the paper is in the write-up phase. If a student or post-doc takes on a project but subsequently hands it off to another student or post-doc, they will most likely be handing over first-authorship to that student or post-doc too (they may also be co-first author, if that is appropriate). All of these issues are open to discussion with Bridget.

<h3>Old Projects</h3>
 
If a student or post-doc drives a project and/or collects a project dataset but does not completely analyze it, write it up, or is actively working on it within a reasonable time frame (which varies for each project) after the end of data collection, Bridget may discuss with that student or post-doc handing the project off to someone who can complete it to expedite publication. If a student or post-doc no longer wishes to work on a project at any time and/or no longer wants to be an author, Bridget will re-assign the project to another individual. This policy is here to prevent data (especially expensive data, e.g., fMRI) from remaining unpublished. Remember the lab philosophy is to “do good science that makes a difference”. We can’t make a difference if research is not being disseminated.

----------

## Human Subjects Research

Adherence to approved IRB protocols is essential, and non-adherence can lead to severe consequences for the entire lab (i.e., we may lose permission to run any research on human participants). Part of respecting our participants means that we must strictly adhere to the IRB protocol for each project. All lab members must read the IRB protocol and consent forms for any project that they are working on. This is also a great way to familiarize yourself with project, and you are also welcome to read the IRB protocols of other projects in the lab that you are not working on to learn more about them. If you are not included in a group that is listed on the IRB (e.g. a volunteer with the lab), you cannot run participants, look at the data, analyze the data, or be in any way involved with the project.
 
Lab members must complete the appropriate training in Human Research that is specified by the specific IRB protocols they are listed in. Speak to your lab manager about the specifics of the IRB protocols you will be listed on and the training you have to do for them, as well as how to access and document the training.
 
If you are starting your own project, you will be expected to write your own IRB protocol (see Bridget and your lab manager for help). If you are starting a study that sits within an existing project, you will be expected to write an amendment to that project’s IRB protocol. If you are working on an existing project, you will need to have your name added to that project’s IRB protocol (see your graduate student, post-doc, or lab manager mentor about this). You must ensure that you have IRB approval before collecting, looking at, or manipulating data from human subjects.
 
Part of the training in Human Subjects research will involve reporting of incidental or unexpected events. If a participant falls ill, becomes very upset, has an accident with the lab equipment, is injured, or otherwise adversely affected by participating in the study, tell Bridget so that we can report this information to the IRB and/or specific funding agencies.