# Funding

----------

Funding for the lab currently comes from four sources:

1. Bridget’s start-up package from UCLA
2. Bridget’s NIMH R00
3. Bridget's Faculty Career Development Award
4. Bridget's NARSAD grant (transferred from Columbia)

Hopefully more money is on its way! The lab manager/s will be responsible for the day-to-day purchasing of items for the lab, however, larger items will be reviewed and approved by Bridget. It might seem like there is a lot of money in the grants (e.g., more than any one of us might have in our bank account at a given time), but after it has paid for everyone’s salaries, all of the participants, scanning etc., there is not a lot left over and it has to stretch for many years. Moreover, it is not clear from where and when the next pot of money will arrive. For this reason, try to engage in the practice of frugality in the lab. Recycle paper, be careful with ordering (e.g., only order what you will likely use before an expiry date), etc. If you see us being wasteful and can think of a way to change that, please let us know.
 
At some point, you will likely be asked to provide a figure or two for a grant Bridget is writing, and/or provide feedback on the grant. At the end of every funding cycle, progress reports for grants are due.
 
Relatedly, you should feel free to read grants Bridget has submitted, whether they are ultimately funded or not. Aside from being a good opportunity to learn how grants are written, this will also allow you to see her vision for the lab in the years ahead. Feel free to ask Bridget to see any of her grants.
